import { useCallback,useEffect,useState } from "react";
import { Pressable,StyleSheet,Text,View } from "react-native";
import TransactionItem from "../../components/TransactionItem";
import { Button,Card,Chip,Empty,Header,Input,Loading,Message,Screen } from "../../components/UI";
import { colors } from "../../constants/theme";
import { useAuth } from "../../context/AuthContext";
import { api } from "../../services/api";
import { dateTime,inr } from "../../utils/format";

export function TransactionsScreen({navigation}){const{user}=useAuth();const[filter,setFilter]=useState("all"),[items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=useCallback(async(f=filter)=>{setLoading(true);setError("");try{setItems((await api.transactions(f)).transactions)}catch(e){setError(e.message)}finally{setLoading(false)}},[filter]);useEffect(()=>navigation.addListener("focus",()=>load()),[navigation,load]);async function choose(f){setFilter(f);await load(f)}return <Screen><Header eyebrow="Cryptographic receipts" title="Transactions" subtitle="Every backend payment has a SHA-256 receipt and optional blockchain anchor."/><View style={styles.filters}>{["all","today","week","month"].map(f=><Pressable key={f} onPress={()=>choose(f)} style={[styles.filter,filter===f&&styles.active]}><Text style={[styles.filterText,filter===f&&{color:colors.bg}]}>{f}</Text></Pressable>)}</View><Message>{error}</Message>{loading?<Loading/>:<Card>{items.length?items.map(x=><TransactionItem key={x._id} item={x} userId={user._id} onPress={()=>navigation.navigate("Receipt",{id:x._id})}/>):<Empty label="No matching transactions"/>}</Card>}</Screen>}

const chainLabel={confirmed:"Confirmed on blockchain",pending:"Blockchain confirmation pending",failed:"Blockchain submission failed",not_anchored:"Not submitted to blockchain"};
export function ReceiptScreen({route,navigation}){const[id]=useState(route.params?.id),[tx,setTx]=useState(route.params?.transaction||null),[error,setError]=useState("");useEffect(()=>{if(id)api.transaction(id).then(d=>setTx(d.transaction)).catch(e=>setError(e.message))},[id]);if(!tx&&!error)return <Loading label="Opening receipt..."/>;const status=tx?.metadata?.blockchainStatus||"not_anchored";return <Screen><Header eyebrow="BlockPay receipt" title={tx?"Payment successful":"Receipt unavailable"} subtitle={tx?.referenceId}/><Message>{error}</Message>{tx?<><Card style={styles.receipt}><Text style={styles.amount}>{inr(tx.amount)}</Text><View style={styles.centerChip}><Chip color={status==="confirmed"?colors.success:status==="failed"?colors.danger:colors.yellow}>{chainLabel[status]||status}</Chip></View><View style={styles.rule}/><Field label="Sender" value={`${tx.senderId?.name||"-"}  @${tx.senderId?.username||"-"}`}/><Field label="Receiver" value={`${tx.receiverId?.name||"-"}  @${tx.receiverId?.username||"-"}`}/><Field label="Date and time" value={dateTime(tx.createdAt)}/><Field label="Reference ID" value={tx.referenceId}/><Field label="SHA-256 receipt hash" value={tx.hash} mono/><Field label="Previous receipt hash" value={tx.previousHash} mono/>{tx.metadata?.blockchainTxHash?<Field label="Blockchain transaction" value={tx.metadata.blockchainTxHash} mono/>:null}{tx.metadata?.blockchainBlockNumber?<Field label="Block number" value={String(tx.metadata.blockchainBlockNumber)}/>:null}{tx.metadata?.blockchainError?<Field label="Last blockchain error" value={tx.metadata.blockchainError}/>:null}</Card><Button title="Verify blockchain receipt" onPress={()=>navigation.navigate("VerifyReceipt",{transaction:tx})}/></>:null}</Screen>}
function Field({label,value,mono}){return <View><Text style={styles.label}>{label}</Text><Text selectable style={[styles.value,mono&&styles.mono]}>{value||"-"}</Text></View>}

export function VerifyReceiptScreen({route}){const tx=route.params?.transaction;const[referenceId,setReferenceId]=useState(tx?.referenceId||""),[hash,setHash]=useState(tx?.hash||""),[local,setLocal]=useState(null),[chain,setChain]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState("");function verifyLocal(){setLocal(Boolean(tx&&referenceId.trim()===tx.referenceId&&hash.trim()===tx.hash&&/^[a-f0-9]{64}$/i.test(hash.trim())))}async function verifyChain(){setBusy(true);setError("");try{setChain((await api.verifyBlockchain(tx._id)).blockchain)}catch(e){setError(e.message)}finally{setBusy(false)}}async function retry(){setBusy(true);setError("");try{const data=await api.retryBlockchain(tx._id);setChain((await api.verifyBlockchain(data.transaction._id)).blockchain)}catch(e){setError(e.message)}finally{setBusy(false)}}return <Screen><Header eyebrow="Proof verification" title="Verify receipt" subtitle="Compare the API receipt locally, then query the deployed smart contract."/><Card><Input label="Reference ID" value={referenceId} onChangeText={setReferenceId}/><Input label="SHA-256 hash" multiline value={hash} onChangeText={setHash} style={styles.mono}/><Button title="Compare local receipt" onPress={verifyLocal}/>{local!==null?<Message type={local?"success":"error"}>{local?"Receipt matches the API record.":"Receipt does not match the API record."}</Message>:null}</Card><Card><Text style={styles.chainTitle}>On-chain verification</Text><Text style={styles.chainCopy}>The backend asks BlockPay.sol whether this reference ID is registered with the exact receipt hash.</Text><Button title="Verify on blockchain" onPress={verifyChain} loading={busy}/>{chain?<Message type={chain.verified?"success":chain.status==="not_configured"?"info":"error"}>{chain.verified?`Confirmed${chain.blockNumber?` in block ${chain.blockNumber}`:""}.`:chain.message||`Verification result: ${chain.status}`}</Message>:null}{tx?.metadata?.blockchainStatus==="failed"||tx?.metadata?.blockchainStatus==="not_anchored"?<Button title="Retry blockchain submission" variant="secondary" onPress={retry} loading={busy}/>:null}<Message>{error}</Message></Card></Screen>}

const styles=StyleSheet.create({filters:{flexDirection:"row",gap:7},filter:{flex:1,paddingVertical:10,borderRadius:10,backgroundColor:colors.panel,alignItems:"center",borderWidth:1,borderColor:colors.border},active:{backgroundColor:colors.teal,borderColor:colors.teal},filterText:{color:colors.muted,fontSize:11,fontWeight:"900",textTransform:"uppercase"},receipt:{alignItems:"stretch"},amount:{color:colors.text,fontSize:34,fontWeight:"900",textAlign:"center"},centerChip:{alignItems:"center"},rule:{height:1,backgroundColor:colors.border,marginVertical:8},label:{color:colors.teal,fontSize:11,fontWeight:"900",textTransform:"uppercase",marginBottom:3},value:{color:colors.text,fontSize:14,lineHeight:20},mono:{fontFamily:"monospace",fontSize:12},chainTitle:{color:colors.text,fontSize:18,fontWeight:"900"},chainCopy:{color:colors.muted,fontSize:13,lineHeight:20}});
