import { useCallback, useEffect, useState } from "react";
import { Alert, StyleSheet, Text, View } from "react-native";
import { Button, Card, Chip, Empty, Header, Input, Message, Screen, SectionTitle, ui } from "../../components/UI";
import { colors } from "../../constants/theme";
import { useAuth } from "../../context/AuthContext";
import { api } from "../../services/api";
import { inr } from "../../utils/format";
export default function RequestsScreen({navigation}){const{user}=useAuth();const[items,setItems]=useState([]);const[form,setForm]=useState({username:'',amount:'',note:''});const[pin,setPin]=useState('1234');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const load=useCallback(async()=>{try{setItems((await api.requests()).requests)}catch(e){setError(e.message)}},[]);useEffect(()=>{const u=navigation.addListener('focus',load);return u},[navigation,load]);async function create(){setBusy(true);setError('');try{await api.requestPayment({...form,amount:Number(form.amount)});setForm({username:'',amount:'',note:''});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}async function act(item,action){try{if(action==='accept')await api.acceptRequest(item._id,pin);else await api.rejectRequest(item._id);await load()}catch(e){Alert.alert('Request failed',e.message)}}return <Screen><Header eyebrow="Collect and settle" title="Payment requests" subtitle="Create a request or respond to one sent to you."/><Card><SectionTitle>New request</SectionTitle><Input label="Payer username" value={form.username} onChangeText={username=>setForm({...form,username})} autoCapitalize="none"/><Input label="Amount" keyboardType="decimal-pad" value={form.amount} onChangeText={amount=>setForm({...form,amount})}/><Input label="Purpose" value={form.note} onChangeText={note=>setForm({...form,note})}/><Message>{error}</Message><Button title="Send request" onPress={create} loading={busy}/><Button title="Split a bill instead" variant="ghost" onPress={()=>navigation.navigate('SplitBill')}/></Card><Input label="PIN used when accepting" secureTextEntry value={pin} onChangeText={setPin}/><SectionTitle>All requests</SectionTitle>{items.length?items.map(item=>{const mine=String(item.payerId?._id)===String(user._id);return <Card key={item._id}><View style={ui.row}><View style={{flex:1}}><Text style={styles.name}>{item.note||'Payment request'}</Text><Text style={ui.muted}>{item.requesterId?.name} asks {item.payerId?.name}</Text></View><Chip color={item.status==='pending'?colors.yellow:colors.teal}>{item.status}</Chip></View><Text style={styles.amount}>{inr(item.amount)}</Text>{mine&&item.status==='pending'?<View style={ui.row}><Button title="Accept" onPress={()=>act(item,'accept')} style={{flex:1}}/><Button title="Reject" variant="danger" onPress={()=>act(item,'reject')} style={{flex:1}}/></View>:null}</Card>}):<Empty label="No payment requests"/>}</Screen>}
const styles=StyleSheet.create({name:{color:colors.text,fontWeight:'900',fontSize:16},amount:{color:colors.text,fontWeight:'900',fontSize:22}});
