import request from "supertest";
import { jest } from "@jest/globals";
import { app } from "../src/app.js";
import { User } from "../src/models/User.js";
import { Wallet } from "../src/models/Wallet.js";
import { Transaction } from "../src/models/Transaction.js";

const register = (username, email = `${username}@test.dev`) => request(app).post("/api/auth/register").send({ name: `${username} User`, email, phone: "9876543210", username, password: "secret1" });
const auth = (token) => ({ Authorization: `Bearer ${token}` });

describe("BlockPay API", () => {
  test("health endpoint responds", async () => { const res = await request(app).get("/api/health"); expect(res.status).toBe(200); expect(res.body.ok).toBe(true); });
  test("registration validates uniqueness and required fields", async () => { expect((await register("alpha")).status).toBe(201); expect((await register("other", "alpha@test.dev")).status).toBe(409); expect((await register("alpha", "new@test.dev")).status).toBe(409); expect((await request(app).post("/api/auth/register").send({})).status).toBe(400); });
  test("login succeeds and rejects wrong credentials", async () => { await register("alpha"); expect((await request(app).post("/api/auth/login").send({ email: "alpha@test.dev", password: "secret1" })).body.token).toBeTruthy(); expect((await request(app).post("/api/auth/login").send({ email: "alpha@test.dev", password: "bad" })).status).toBe(401); });
  test("protected endpoints reject missing and invalid JWT", async () => { expect((await request(app).get("/api/wallet")).status).toBe(401); expect((await request(app).get("/api/wallet").set("Authorization", "Bearer invalid")).status).toBe(401); });
  test("transfer atomically updates balances and creates receipt", async () => { const a=await register("alpha"); await register("bravo"); const res=await request(app).post("/api/wallet/transfer").set(auth(a.body.token)).send({username:"bravo",amount:500,note:"Lunch",pin:"1234"}); expect(res.status).toBe(201); expect(res.body.transaction.hash).toMatch(/^[a-f0-9]{64}$/); const wallets=await Wallet.find().sort({balance:1}); expect(wallets.map(x=>x.balance)).toEqual([9500,10500]); });
  test("a failed receipt write rolls back both wallet changes", async () => { const a=await register("alpha"); await register("bravo"); const create=jest.spyOn(Transaction,"create").mockRejectedValueOnce(new Error("forced receipt failure")); const res=await request(app).post("/api/wallet/transfer").set(auth(a.body.token)).send({username:"bravo",amount:500,pin:"1234"}); create.mockRestore(); expect(res.status).toBe(500); const wallets=await Wallet.find(); expect(wallets.map(x=>x.balance)).toEqual([10000,10000]); expect(await Transaction.countDocuments()).toBe(0); });
  test.each([0,-1])("rejects invalid transfer amount %s", async(amount)=>{const a=await register("alpha");await register("bravo");expect((await request(app).post("/api/wallet/transfer").set(auth(a.body.token)).send({username:"bravo",amount,pin:"1234"})).status).toBe(400)});
  test("rejects self, unknown receiver, insufficient funds and wrong PIN", async()=>{const a=await register("alpha");const h=auth(a.body.token);expect((await request(app).post("/api/wallet/transfer").set(h).send({username:"alpha",amount:1,pin:"1234"})).status).toBe(400);expect((await request(app).post("/api/wallet/transfer").set(h).send({username:"nobody",amount:1,pin:"1234"})).status).toBe(404);await register("bravo");expect((await request(app).post("/api/wallet/transfer").set(h).send({username:"bravo",amount:20000,pin:"1234"})).status).toBe(400);expect((await request(app).post("/api/wallet/transfer").set(h).send({username:"bravo",amount:1,pin:"0000"})).status).toBe(403)});
  test("history and receipts enforce participant access", async()=>{const a=await register("alpha");await register("bravo");const c=await register("charlie");const tx=(await request(app).post("/api/wallet/transfer").set(auth(a.body.token)).send({username:"bravo",amount:10,pin:"1234"})).body.transaction;expect((await request(app).get("/api/transactions").set(auth(a.body.token))).body.transactions).toHaveLength(1);expect((await request(app).get(`/api/transactions/${tx._id}`).set(auth(c.body.token))).status).toBe(403)});
  test("blockchain verification is honest when anchoring is disabled",async()=>{const a=await register("alpha");await register("bravo");const h=auth(a.body.token);const tx=(await request(app).post("/api/wallet/transfer").set(h).send({username:"bravo",amount:10,pin:"1234"})).body.transaction;const result=await request(app).get(`/api/transactions/${tx._id}/blockchain/verify`).set(h);expect(result.status).toBe(200);expect(result.body.blockchain).toMatchObject({available:false,verified:false,status:"not_configured"});expect((await request(app).post(`/api/transactions/${tx._id}/blockchain/retry`).set(h)).body.transaction.metadata.blockchainStatus).toBe("not_anchored")});
  test("payment requests can be accepted and rejected",async()=>{const a=await register("alpha"),b=await register("bravo");const made=await request(app).post("/api/transactions/request").set(auth(a.body.token)).send({username:"bravo",amount:50,note:"Tea"});expect((await request(app).post(`/api/transactions/accept/${made.body.request._id}`).set(auth(b.body.token)).send({pin:"1234"})).status).toBe(201);const second=await request(app).post("/api/transactions/request").set(auth(a.body.token)).send({username:"bravo",amount:20});expect((await request(app).post(`/api/transactions/reject/${second.body.request._id}`).set(auth(b.body.token)).send({})).body.request.status).toBe("rejected")});
  test("split bill uses backend rounding",async()=>{const a=await register("alpha");await register("bravo");await register("charlie");const res=await request(app).post("/api/transactions/split").set(auth(a.body.token)).send({title:"Pizza",amount:100,members:["bravo","charlie"]});expect(res.body.perHead).toBe(33.34);expect(res.body.requests).toHaveLength(2)});
  test("friend search, add, list and remove work",async()=>{const a=await register("alpha"),b=await register("bravo");const h=auth(a.body.token);expect((await request(app).get("/api/users/search?q=bra").set(h)).body.users[0].username).toBe("bravo");await request(app).post("/api/friends").set(h).send({username:"bravo"});expect((await request(app).get("/api/friends").set(h)).body.friends).toHaveLength(1);expect((await request(app).delete(`/api/friends/${b.body.user._id}`).set(h)).status).toBe(204)});
  test("QR generation and validation use BLOCKPAY_QR",async()=>{const a=await register("alpha");const h=auth(a.body.token);const generated=await request(app).post("/api/qr/generate").set(h).send({amount:25,purpose:"Snack"});expect(generated.body.payload.type).toBe("BLOCKPAY_QR");expect((await request(app).post("/api/qr/scan").set(h).send({payload:generated.body.payload})).body.username).toBe("alpha");expect((await request(app).post("/api/qr/scan").set(h).send({payload:{type:"OTHER"}})).status).toBe(400)});
  test("notifications can be marked read",async()=>{const a=await register("alpha"),b=await register("bravo");await request(app).post("/api/wallet/transfer").set(auth(a.body.token)).send({username:"bravo",amount:10,pin:"1234"});const h=auth(b.body.token);const notes=(await request(app).get("/api/notifications").set(h)).body.notifications;expect((await request(app).put(`/api/notifications/${notes[0]._id}/read`).set(h)).body.notification.read).toBe(true);expect((await request(app).put("/api/notifications/read-all").set(h)).status).toBe(200)});
  test("admin summary is role protected",async()=>{const a=await register("alpha");expect((await request(app).get("/api/admin/summary").set(auth(a.body.token))).status).toBe(403);await User.updateOne({_id:a.body.user._id},{role:"admin"});expect((await request(app).get("/api/admin/summary").set(auth(a.body.token))).status).toBe(200)});
});
