import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { ActivityIndicator,KeyboardAvoidingView,Platform,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors,gradients,radius,shadow,spacing } from "../constants/theme";

export function Screen({children,scroll=true,refreshing=false,onRefresh,contentStyle}){const body=scroll?<ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={[styles.content,contentStyle]} keyboardShouldPersistTaps="handled" refreshControl={onRefresh?<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor={colors.purple} colors={[colors.purple]}/>:undefined}>{children}</ScrollView>:<View style={[styles.content,{flex:1},contentStyle]}>{children}</View>;return <SafeAreaView style={styles.safe} edges={["top","bottom"]}><View pointerEvents="none" style={styles.glowOne}/><View pointerEvents="none" style={styles.glowTwo}/><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==="ios"?"padding":undefined}>{body}</KeyboardAvoidingView></SafeAreaView>}
export function Header({eyebrow,title,subtitle,right}){return <View style={styles.header}><View style={{flex:1}}>{eyebrow?<Text style={styles.eyebrow}>{eyebrow}</Text>:null}<Text style={styles.title}>{title}</Text>{subtitle?<Text style={styles.subtitle}>{subtitle}</Text>:null}</View>{right}</View>}
export function Card({children,style,gradient=false}){return gradient?<LinearGradient colors={gradients.surface} start={{x:0,y:0}} end={{x:1,y:1}} style={[styles.card,style]}>{children}</LinearGradient>:<View style={[styles.card,style]}>{children}</View>}
export function Button({title,onPress,variant="primary",loading,disabled,style,icon}){const inner=loading?<ActivityIndicator color={colors.white}/>:<View style={styles.buttonInner}>{icon?<Ionicons name={icon} size={18} color={colors.white}/>:null}<Text style={styles.buttonText}>{title}</Text></View>;return <Pressable accessibilityRole="button" onPress={onPress} disabled={disabled||loading} style={({pressed})=>[pressed&&{transform:[{scale:.985}]},(disabled||loading)&&{opacity:.48},style]}>{variant==="primary"?<LinearGradient colors={gradients.primary} start={{x:0,y:0}} end={{x:1,y:1}} style={[styles.button,shadow.glow]}>{inner}</LinearGradient>:<View style={[styles.button,styles[`button_${variant}`]]}>{inner}</View>}</Pressable>}
export function Input({label,error,multiline,style,...props}){return <View style={styles.field}>{label?<Text style={styles.label}>{label}</Text>:null}<View style={[styles.inputShell,error&&{borderColor:colors.danger}]}><TextInput accessibilityLabel={props.accessibilityLabel||label} placeholderTextColor={colors.subtle} selectionColor={colors.purple} multiline={multiline} style={[styles.input,multiline&&{minHeight:92,textAlignVertical:"top"},style]} {...props}/></View>{error?<Text style={styles.error}>{error}</Text>:null}</View>}
export function Chip({children,color=colors.teal}){return <View style={[styles.chip,{backgroundColor:`${color}18`}]}><View style={[styles.chipDot,{backgroundColor:color}]}/><Text style={[styles.chipText,{color}]}>{children}</Text></View>}
export function Message({children,type="error"}){if(!children)return null;const c=type==="success"?colors.success:type==="info"?colors.blue:colors.danger;const icon=type==="success"?"checkmark-circle":type==="info"?"information-circle":"alert-circle";return <View style={[styles.message,{borderColor:`${c}55`,backgroundColor:`${c}10`}]}><Ionicons name={icon} size={18} color={c}/><Text style={{color:c,flex:1,lineHeight:19,fontWeight:"600"}}>{children}</Text></View>}
export function Loading({label="Loading BlockPay..."}){return <View style={styles.center}><View style={styles.loader}><ActivityIndicator size="large" color={colors.teal}/></View><Text style={styles.subtitle}>{label}</Text></View>}
export function Empty({label="Nothing here yet"}){return <View style={styles.empty}><View style={styles.emptyIcon}><Ionicons name="sparkles-outline" size={26} color={colors.purple}/></View><Text style={styles.emptyTitle}>{label}</Text><Text style={styles.emptyCopy}>Your activity will appear here.</Text></View>}
export function SectionTitle({children,action}){return <View style={styles.sectionRow}><Text style={styles.sectionTitle}>{children}</Text>{action}</View>}
export const ui=StyleSheet.create({row:{flexDirection:"row",alignItems:"center",gap:spacing.sm},wrap:{flexDirection:"row",flexWrap:"wrap",gap:spacing.sm},muted:{color:colors.muted,lineHeight:20},strong:{color:colors.text,fontWeight:"800"},amount:{color:colors.text,fontSize:30,fontWeight:"900",letterSpacing:-1}});
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},content:{paddingHorizontal:spacing.md,paddingTop:spacing.md,gap:spacing.md,paddingBottom:42},glowOne:{position:"absolute",width:260,height:260,borderRadius:130,backgroundColor:"rgba(128,107,255,0.10)",top:-120,right:-100},glowTwo:{position:"absolute",width:220,height:220,borderRadius:110,backgroundColor:"rgba(84,229,209,0.055)",bottom:80,left:-140},header:{flexDirection:"row",gap:spacing.md,alignItems:"center",marginBottom:4},eyebrow:{color:colors.teal,fontSize:11,fontWeight:"900",letterSpacing:1.8,textTransform:"uppercase"},title:{color:colors.text,fontSize:30,fontWeight:"900",letterSpacing:-1,marginTop:4},subtitle:{color:colors.muted,fontSize:14,lineHeight:21,marginTop:5},card:{backgroundColor:colors.panel,borderColor:colors.borderSoft,borderWidth:1,borderRadius:radius.md,padding:spacing.md,gap:spacing.sm,...shadow.card},button:{minHeight:52,paddingHorizontal:spacing.md,borderRadius:radius.sm,alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:"rgba(255,255,255,0.13)"},button_secondary:{backgroundColor:colors.panelHighlight,borderColor:colors.border},button_danger:{backgroundColor:"rgba(255,107,122,.09)",borderColor:"rgba(255,107,122,.35)"},button_ghost:{backgroundColor:"transparent",borderColor:colors.border},buttonInner:{flexDirection:"row",alignItems:"center",justifyContent:"center",gap:8},buttonText:{color:colors.white,fontSize:14,fontWeight:"900",letterSpacing:.2},field:{gap:7},label:{color:colors.muted,fontSize:12,fontWeight:"800",letterSpacing:.3},inputShell:{backgroundColor:colors.bgElevated,borderColor:colors.border,borderWidth:1,borderRadius:radius.sm},input:{color:colors.text,minHeight:52,paddingHorizontal:15,fontSize:15},error:{color:colors.danger,fontSize:12},chip:{borderRadius:radius.pill,paddingHorizontal:10,paddingVertical:6,flexDirection:"row",alignItems:"center",gap:6,alignSelf:"flex-start"},chipDot:{width:6,height:6,borderRadius:3},chipText:{fontSize:10,fontWeight:"900",textTransform:"uppercase",letterSpacing:.6},message:{borderWidth:1,borderRadius:radius.sm,padding:12,flexDirection:"row",alignItems:"center",gap:9},center:{alignItems:"center",justifyContent:"center",gap:spacing.sm,minHeight:150},loader:{width:58,height:58,borderRadius:20,backgroundColor:colors.panel,alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:colors.border},empty:{alignItems:"center",paddingVertical:28,gap:6},emptyIcon:{width:54,height:54,borderRadius:18,backgroundColor:"rgba(128,107,255,.12)",alignItems:"center",justifyContent:"center",marginBottom:5},emptyTitle:{color:colors.text,fontSize:15,fontWeight:"800"},emptyCopy:{color:colors.muted,fontSize:12},sectionRow:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginTop:4},sectionTitle:{color:colors.text,fontSize:18,fontWeight:"900",letterSpacing:-.3}});
