services:
  mongo:
    image: mongo:7
    container_name: blockpay-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - blockpay_mongo:/data/db

volumes:
  blockpay_mongo:
