import { CameraView, useCameraPermissions } from "expo-camera";
import { useIsFocused } from "@react-navigation/native";
import { useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import { Button, Card, Header, Message, Screen } from "../../components/UI";
import { colors } from "../../constants/theme";
import { api } from "../../services/api";
import { parseBlockPayQr } from "../../utils/qr";
export default function ScanQrScreen({navigation}){const[permission,requestPermission]=useCameraPermissions();const[scanned,setScanned]=useState(false);const[error,setError]=useState('');const isFocused=useIsFocused();async function handle({data}){if(scanned)return;setScanned(true);setError('');try{parseBlockPayQr(data);const normalized=await api.scanQr(data);navigation.replace('SendMoney',{username:normalized.username,amount:normalized.amount,note:normalized.note})}catch(e){setError(e.message)}}if(!permission)return <Screen><Header title="Scan QR"/><Card><Text style={styles.copy}>Checking camera permission...</Text></Card></Screen>;if(!permission.granted)return <Screen><Header eyebrow="Camera access required" title="Scan BlockPay QR"/><Card><Text style={styles.copy}>BlockPay uses the camera only while this scanner is open.</Text><Button title="Allow camera" onPress={requestPermission}/><Message>{permission.canAskAgain?'':'Camera permission is blocked. Enable it in device settings.'}</Message></Card></Screen>;return <Screen scroll={false} contentStyle={{padding:0}}><View style={styles.shell}>{isFocused?<CameraView style={StyleSheet.absoluteFill} facing="back" barcodeScannerSettings={{barcodeTypes:['qr']}} onBarcodeScanned={scanned?undefined:handle}/>:null}<View style={styles.overlay}><Header eyebrow="BLOCKPAY QR" title="Align the code" subtitle="Only BLOCKPAY_QR payloads are accepted."/><View style={styles.frame}/><Message>{error}</Message>{scanned?<Button title="Scan again" onPress={()=>{setScanned(false);setError('')}}/>:null}</View></View></Screen>}
const styles=StyleSheet.create({shell:{flex:1,backgroundColor:colors.bg},overlay:{flex:1,padding:18,justifyContent:'space-between',backgroundColor:'rgba(7,17,31,.28)'},frame:{alignSelf:'center',width:260,height:260,borderWidth:3,borderColor:colors.teal,borderRadius:24},copy:{color:colors.muted,lineHeight:20}});
