import { useEffect, useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import { Card, Empty, Header, Loading, Message, Screen } from "../../components/UI";
import { colors } from "../../constants/theme";
import { useAuth } from "../../context/AuthContext";
import { api } from "../../services/api";
import { dateTime, inr } from "../../utils/format";
export default function AdminScreen(){const{user}=useAuth();const[data,setData]=useState(null);const[error,setError]=useState('');useEffect(()=>{if(user.role!=='admin'){setError('Administrator access is required.');return}api.adminSummary().then(setData).catch(e=>setError(e.message))},[user.role]);return <Screen><Header eyebrow="Role-protected analytics" title="Admin dashboard" subtitle="Operational summary for authorised administrators."/><Message>{error}</Message>{!data&&!error?<Loading/>:data?<><View style={styles.metrics}><Metric label="Users" value={data.totalUsers}/><Metric label="Payments" value={data.totalPayments}/><Metric label="Volume" value={inr(data.totalVolume)}/></View><Text style={styles.heading}>Latest transfers</Text>{data.latestTransactions?.length?data.latestTransactions.map(x=><Card key={x._id}><Text style={styles.amount}>{inr(x.amount)}</Text><Text style={styles.copy}>{x.senderId?.name} → {x.receiverId?.name}</Text><Text style={styles.copy}>{dateTime(x.createdAt)}</Text></Card>):<Empty label="No transfers yet"/>}<Text style={styles.heading}>High-value demo transfers</Text>{data.fraudAlerts.length?data.fraudAlerts.map(x=><Card key={x._id}><Text style={styles.amount}>{inr(x.amount)}</Text><Text style={styles.copy}>{x.senderId?.name} → {x.receiverId?.name}</Text><Text style={styles.copy}>{dateTime(x.createdAt)}</Text></Card>):<Empty label="No high-value transfers"/>}</>:null}</Screen>}
function Metric({label,value}){return <Card style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text></Card>}
const styles=StyleSheet.create({metrics:{flexDirection:'row',gap:8},metric:{flex:1,padding:12},metricLabel:{color:colors.muted,fontSize:11},metricValue:{color:colors.teal,fontSize:17,fontWeight:'900'},heading:{color:colors.text,fontSize:18,fontWeight:'900'},amount:{color:colors.text,fontSize:20,fontWeight:'900'},copy:{color:colors.muted}});
